### ISSUE TITLE
Save pins in a geojson file

### ISSUE THREAD

**Issue by mibalas** [wwwouaiebe/leaflet.marker.pin#4]
Hi, is there any way to save the pins created in a geojson file automatically?

I want to do a collaborative map and users will insert new pins on the map and I want to write to a geojson file.

thanks

**Comment by wwwouaiebe** [comment]
Saving to and restoring from a GeoJSON object is now possible with the v1.2.1dev branch. See the toGeoJSON  ( ) and pointToLayer ( ) methods in the documentation.
Notice:
- saving and restoring is enabled to an object, not to a file. If you will save to a file, you have to implement this part.
- the branch v1.2.1dev is currently the development branch. Can be unstable!

**Comment by wwwouaiebe** [comment]
Done. See release v1.2.1
