### ISSUE TITLE
custom html template for adding new pin 

### ISSUE THREAD

**Issue by TharaCJ** [wwwouaiebe/leaflet.marker.pin#7]
Is there any option to override the standard template and display custom html while adding a new pin?

**Comment by wwwouaiebe** [comment]
No there isn't any possibility to do this. I'm busy to write a new project where this is possible. This project is quite finished and work correctly with Firefox. It's remains perhaps some bugs with MS Edge (testing on going) and the english documentation to do ( a part of the doc in french is already there). 
See [https://github.com/wwwouaiebe/leaflet.TravelNotes](https://github.com/wwwouaiebe/leaflet.TravelNotes)

**Comment by wwwouaiebe** [comment]
Closing this issue since leaflet.TravelNotes is released.
